### PR TITLE
Removed reference to authenticator.constructor.name and used new authenticator.getName method

### LINKED ISSUE #92: Authenticator names are being mangled by minification
When using the ual-reactjs-renderer within an application that uses a minification build process, the names of the authenticators are getting mangled and corrupting the local storage value for `UALLoggedInAuthType`. The value saved in local storage ends up being the minified value (like `n`) and causes session persistence to break. 

This is happening because it's currently using the constructor value which seems to be a valid target for mangling:

https://github.com/EOSIO/ual-reactjs-renderer/blob/0eaaf1ee9b7f941c92a12ee212e8bdcb8621e674/src/components/provider/UALProvider.js#L170

I discovered this bug while debugging why session persistence wasn't functioning within [eoscostarica/eos-rate](https://github.com/eoscostarica/eos-rate). This is a react-scripts application, which has built-in minification and mangling. If you log in using any authenticator on eosrate.io, you'll see the local storage value of `UALLoggedInAuthType` being set improperly and the session won't persist. 

Perhaps authenticators need to implement a string value of their name which can be used, as opposed to using the constructor's name? I don't know the appropriate solution, but figured I'd raise the issue.

### PR DESCRIPTION
**Pull request by aaroncox**
Fixes #92 

## Change Description

Changed 3 instances where the authenticator constructors name was being used instead of the getName() method.

This prevents the `UALLoggedInAuthType` localStorage value from getting mangled by webpack/etc. 

An example of the value getting set improperly:

image

The value shows as `n` (the mangled name), as opposed to `anchor` (the original class name or value of `getName()`).

This PR is a follow up for: #92, #95, and #96.

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by jlamarr22** [comment]
@aaroncox Thanks for logging this. There are two more references that need to be updated and the package.json needs to be bumped to release this as a patch, so I created a new PR for this here: https://github.com/EOSIO/ual-reactjs-renderer/pull/98

**Comment by aaroncox** [comment]
@jlamarr22 Ahh good catches, I honestly didn't even notice one of those. I do wonder if there's value in having them both though. The way I interpreted these two values was that the text within the styles was more the decorative / user facing value, where as the result returned by `getName()` was going to be the programatic name of the authenticator itself. 

For example, with our plugin we might do:

- Style Name: `Anchor Wallet` (cased, spaces, user facing value)
- getName returns: `anchor` (all lower case, no spaces, "slugified")

I don't know if this matters a whole lot, but figured I'd mention it as potentially a different approach.

**Comment by jlamarr22** [comment]
@aaroncox Makes sense to me for more customization actually -- good point. If you bump this PR's version to `0.3.1`, we can get it merged and released tomorrow.

**Comment by aaroncox** [comment]
Done, and also included the few other tweaks you had made in your PR as well 👍

**Review by jlamarr22 — APPROVED** [review]

**Comment by prfigueroa** [comment]
Gentlemen, thank you for getting the fix in.  I've tested it in the Acueos staging environment and I can confirm the issue has been fixed. Thanks.

**Pull request merged**
